/**
 * Canary — x86-64 Linux ELF emulator in WebAssembly.
 *
 * Drop-in compatible with the CheerpX API surface (cheerpx-meta),
 * with full x86-64 support where CheerpX only supports 32-bit.
 */

// The WASM module is bundled by wasm-pack into canary_wasm.js
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore — generated by wasm-pack
import initWasm, { CanaryRuntime } from "../../crates/canary-wasm/pkg/canary_wasm.js";

export * from "./devices.js";
export * from "./linux.js";
export { Linux, DataDevice, IDBDevice, HttpBytesDevice, WebDevice, OverlayDevice } from "./linux.js";
